# Attempt at setting up a custom Fedora container for Rust
# development.
#
# Tools provided:
# - rustup
# - rust
# - neovim configured for Rust
# - tmux
#
# Anything else, I don't know... we will see

FROM fedora:39

WORKDIR /work

# Blah blah blah
# .......
        
