apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - image: mongo:3
          name: db
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
      restartPolicy: Always
